server {
    listen 80;
    server_name 74.248.233.128 tickwise.polandcentral.cloudapp.azure.com;

    location /static/ {
        alias /opt/tickwise/staticfiles/;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate max-age=0";
    }

    location /media/ {
        alias /opt/tickwise/media/;
    }

    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}